basePath: /
host: fedhirasyaila.heroku.com
info:
  contact:
    email: sfedhira@gmail.com
    name: API Support
    url: https://github.com/Fedhira
  description: This is a sample swagger server.
  title: TES SWAG
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
